apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  labels: 
    app: trial
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: rkhudoyberdiev/trial-app:latest
        imagePullPolicy: Always
        ports:
        - name: trialport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels: 
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      protocol: TCP
      port: 8082
      targetPort: trialport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  annotations: 
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backend
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default